// Merges per-language menu JSON (from PDF extraction) into data/menu.js and cross-checks languages.
// Usage: node tools/build-menu.mjs <folder-with-lang-json>
import fs from "fs"; import path from "path";
const src = process.argv[2]; const out = new URL("../data/menu.js", import.meta.url);
const ORDER = ["en","es","de","fr","it","nl","da","sv","no","fi"];
const langs = ORDER.filter(l => fs.existsSync(path.join(src, l + ".json")));
const docs = Object.fromEntries(langs.map(l => [l, JSON.parse(fs.readFileSync(path.join(src, l + ".json"), "utf8"))]));
const base = docs[langs[0]]; const problems = [];
const tr = (get) => Object.fromEntries(langs.map(l => [l, get(docs[l])]).filter(([, v]) => v != null && v !== ""));
// Words that usually mean a dropped fi/fl ligature in PDF text
const ligature = /(^|[\s(“"])(Tunsk|øde|øte|Tonsk|bläcksk|oxlé|sklé|sk|letto|let|ambé|ambati|knoook|kiplet|vislet|indrelet|sisälee|Thunsch|Rindeisch|Rinderlet)(?=$|[\s,.)”"])/u;
const categories = base.categories.map(bc => {
  const cats = Object.fromEntries(langs.map(l => [l, docs[l].categories.find(c => c.id === bc.id)]));
  for (const l of langs) if (!cats[l]) problems.push(`${l}: missing category ${bc.id}`);
  const items = bc.items.map(bi => {
    const per = Object.fromEntries(langs.map(l => [l, cats[l]?.items.find(i => i.n === bi.n)]));
    for (const l of langs) {
      const it = per[l];
      if (!it) { problems.push(`${l}: item ${bi.n} not in ${bc.id}`); continue; }
      const p = JSON.stringify(it.price ?? it.prices), bp = JSON.stringify(bi.price ?? bi.prices);
      if (p !== bp && !(it.prices && bi.prices)) problems.push(`price differs #${bi.n}: ${langs[0]}=${bp} ${l}=${p}`);
      for (const s of [it.name, it.desc, it.detail]) if (s && ligature.test(s)) problems.push(`${l}: possible lost ligature #${bi.n}: "${s}"`);
    }
    const o = { n: bi.n, name: Object.fromEntries(langs.map(l => [l, per[l]?.name]).filter(([,v])=>v)) };
    const desc = Object.fromEntries(langs.map(l => [l, per[l]?.desc]).filter(([,v])=>v)); if (Object.keys(desc).length) o.desc = desc;
    const det = Object.fromEntries(langs.map(l => [l, per[l]?.detail]).filter(([,v])=>v)); if (Object.keys(det).length) o.detail = det;
    if (bi.prices) o.prices = bi.prices.map((p, k) => ({ value: p.value, label: Object.fromEntries(langs.map(l => [l, per[l]?.prices?.[k]?.label]).filter(([,v])=>v)) }));
    else o.price = bi.price;
    return o;
  });
  const c = { id: bc.id, title: Object.fromEntries(langs.map(l => [l, cats[l]?.title]).filter(([,v])=>v)), items };
  const note = Object.fromEntries(langs.map(l => [l, cats[l]?.note]).filter(([,v])=>v));
  // Un-numbered option boxes like the sauces: "3.50 - Mushroom, Pepper, BBQ" -> one price + option list
  const opt = Object.values(note)[0]?.match(/^(\d+[.,]\d{2})\s*[-–—:]\s*(.+)$/s);
  if (!bc.items.length && opt) {
    c.optionPrice = parseFloat(opt[1].replace(",", "."));
    c.options = Object.fromEntries(Object.entries(note).map(([l, s]) => [l, s.replace(/^\d+[.,]\d{2}\s*[-–—:]\s*/, "").split(/\s*[,\n]\s*|\s+-\s*/).map(x => x.replace(/^-/, "").trim()).filter(Boolean)]));
    const lens = new Set(Object.values(c.options).map(a => a.length)); if (lens.size > 1) problems.push(`${bc.id}: option counts differ across languages ${JSON.stringify(Object.fromEntries(Object.entries(c.options).map(([l,a])=>[l,a.length])))}`);
  } else if (Object.keys(note).length) c.note = note;
  if (bc.groups) c.groups = bc.groups.map((g, k) => ({ id: g.id, from: g.from, to: g.to, title: Object.fromEntries(langs.map(l => [l, cats[l]?.groups?.[k]?.title]).filter(([,v])=>v)) }));
  return c;
});
// Apply data/corrections.json (typo fixes on top of the PDF text)
const corrFile = new URL("../data/corrections.json", import.meta.url);
if (fs.existsSync(corrFile)) {
  const { fixes } = JSON.parse(fs.readFileSync(corrFile, "utf8")); let applied = 0;
  for (const fx of fixes) {
    const target = fx.cat ? categories.find(c => c.id === fx.cat) : categories.flatMap(c => c.items).find(i => i.n === fx.n);
    const obj = target && target[fx.field];
    if (obj && typeof obj[fx.lang] === "string" && obj[fx.lang].includes(fx.from)) { obj[fx.lang] = obj[fx.lang].replace(fx.from, fx.to); applied++; }
    else problems.push(`correction not applied (text not found): ${JSON.stringify(fx)}`);
  }
  console.log(`corrections applied: ${applied}/${fixes.length}`);
}
const count = categories.reduce((a, c) => a + c.items.length, 0);
const menu = { languages: langs, languageNames: tr(d => d.languageName), footnote: tr(d => d.footnotes?.[0]), categories };
fs.writeFileSync(out, "// Generated by tools/build-menu.mjs from the PDF extraction. Edit the JSON and re-run, or edit here directly.\nwindow.MENU = " + JSON.stringify(menu, null, 1) + ";\n");
console.log(`languages: ${langs.join(" ")} | categories: ${categories.length} | items: ${count}`);
console.log(problems.length ? "PROBLEMS:\n- " + problems.join("\n- ") : "no problems");
const issues = langs.flatMap(l => (docs[l].issues || []).map(i => `[${l}] ${typeof i === "string" ? i : JSON.stringify(i)}`));
fs.writeFileSync(path.join(src, "_issues.txt"), issues.join("\n"));
console.log(`agent-reported issues: ${issues.length} (saved to _issues.txt)`);
